name: import deployment configuration files

on:
  workflow_call:
    inputs:
      libref:
        required: true
        type: string
        default: master

      targetdir:
        required: true
        type: string
    #outputs:
    #  result:
    #    value: ${{ jobs.lookup.outputs.result }}

jobs:
  lookup:
    runs-on: ubuntu-latest
    #outputs:
    #  result:
    #    ${{ steps.fetch.outputs.value }}

    steps:
      - name: 'Context Dump'
        run: |
          echo "github event_name: " ; echo '${{ github.event_name }}'
          echo "github context: " ; echo '${{ toJSON(github) }}'
          echo "inputs context: " ; echo '${{ toJSON(inputs) }}'
          echo "env context: " ; echo '${{ toJSON(env) }}'
          echo "github environment in runner:"; /bin/env
          echo '-----'

      - uses: actions/checkout@v3
        with:
          #repository: ${{ github.action_repository }}
          repository: shards-of-blue/moose-droppings
          ref: ${{inputs.libref}}
          path: moose

      - uses: actions/upload-artifact@v3
        with:
          name: moose-drops
          path: |
            moose/conf/*.yaml
            moose/tf/

      - name: 'Fetch'
        id: 'fetch'
        run: |
          echo "CMD: cp -p *.yaml ${{ inputs.targetdir }}"
        #  /bin/bash -c "cp -p moose/*.yaml ${{ inputs.targetdir }}"
#
